name: Build & Push Temporal Worker

on:
  push:
    branches:
      - main  # or the branch you want to track

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Build JAR
      - name: Build JAR
        run: ./gradlew clean build -x test

      # 4. Log in to Docker Hub (optional if pushing)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t rahulnigamfzd/orderprocessor-worker:latest .

      # 6. Push Docker image (optional)
      - name: Push Docker image
        run: docker push rahulnigamfzd/orderprocessor-worker:latest
